configuracoes = {
  "control1" => {
    "images"   => "ubuntu/jammy64",
    "memory"  => "4048",
    "cpu"     => "4",
    "ip"      => "101"
  },
  "control2" => {
    "images"   => "ubuntu/jammy64",
    "memory"  => "4048",
    "cpu"     => "4",
    "ip"      => "101"
  },
  "worker1" => {
    "images"   => "ubuntu/jammy64",
    "memory"  => "6048",
    "cpu"     => "4",
    "ip"      => "102"
  },
}

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  configuracoes.each do |nome,capacity|
    config.vm.define "#{nome}" do |maquina|
      maquina.vm.box    = "#{capacity["images"]}"
      # maquina.vm.network "private_network", ip: "10.5.25.#{capacity["ip"]}"
      maquina.vm.network "public_network", bridge: "Killer(R) Wi-fi 6 AX 1650i 1600MHz Wireless Network Adapter (20 1NGW)"
      maquina.vm.hostname = "#{nome}.myckacertificate.com"
      maquina.vm.provider "virtualbox" do |customizando|
        customizando.cpus = capacity["cpu"]
        customizando.memory = capacity["memory"]
        customizando.name = "#{nome}.myckacertificate.com"
        # customizando.customize [ "modifyvm", :id, "--groups", "/CKASampleExam2" ] 
    end
  end
  end
end
